server:
  port: 8080
  context-path: /todo-app

spring:
  profiles:
    active: default
  datasource:
    url: jdbc:mysql://localhost:3306/todoapp?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;
    username: root
    password: 12345
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      ddl-auto: update

  jackson:
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    org.hibernate.SQL: trace
---

spring:
  profiles: init

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: trace
